export const JWT_CONFIG = {
  ACCESS_TOKEN_EXPIRY: '15m',
  REFRESH_TOKEN_EXPIRY: '7d',
  REFRESH_TOKEN_COOKIE_NAME: 'refreshToken',
};

export const SECURITY_CONFIG = {
  BCRYPT_ROUNDS: 12,
  MAX_LOGIN_ATTEMPTS: 5,
  MAX_OTP_ATTEMPTS: 5,                     // Max wrong guesses before OTP is locked
  ACCOUNT_LOCK_DURATION: 15 * 60 * 1000,  // 15 minutes in ms
  OTP_EXPIRY_HOURS: 24,                    // Email verification OTP: 24 hours
  OTP_RESET_EXPIRY_MINUTES: 15,            // Password reset OTP: 15 minutes (tighter window)
  PASSWORD_RESET_TOKEN_EXPIRY_HOURS: 1,
};

export const ROLES = {
  ADMIN: 'ADMIN',
  JUDGE: 'JUDGE',
  CANDIDATE: 'CANDIDATE',
} as const;

export const AUDIT_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  OTP_RESENT: 'OTP_RESENT',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  SESSION_REFRESHED: 'SESSION_REFRESHED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_AUTO_UNLOCKED: 'ACCOUNT_AUTO_UNLOCKED',
  AUTH_VERIFICATION_FAILED: 'AUTH_VERIFICATION_FAILED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  SUSPICIOUS_OTP_EXHAUSTED: 'SUSPICIOUS_OTP_EXHAUSTED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
} as const;

export type AuditAction = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];
